import { getBridgeApiBase } from "../phase3/client.ts";

export type OrganizationType = "brand" | "retailer" | "dispensary";
export type ProfileStatus = "draft" | "pending_review" | "correction_requested" | "approved" | "rejected" | "suspended";
export type ContactRequestStatus = "new" | "viewed" | "responded" | "closed";
export type ContactPreference = "email" | "phone" | "either";
export type DirectorySort = "name_asc" | "name_desc";
export type AdminAccountChoice = "standard" | "sales_rep" | "admin";
export type Business = { id: string; organizationId: string; legalName: string; dbaName: string | null; status: string };
export type DirectoryLink = { type: "website" | "menu" | "product" | "other"; label: string; url: string; sortOrder: number };
export type DirectoryProfile = { id?: string; organizationId?: string; businessId?: string; slug: string; displayName: string; summary: string | null; story: string | null; businessType: OrganizationType | null; categories: string[]; city: string | null; state: string | null; region: string | null; publicContact: { email: string | null; phone: string | null }; license: { type: string | null; number: string | null } | null; links: DirectoryLink[]; logoUrl: string | null; status?: ProfileStatus; hasPublishedVersion?: boolean; submittedAt?: string | null; reviewedAt?: string | null; workflowReason?: string | null; approvedAt?: string | null; legalName?: string; dbaName?: string | null; businessName?: string; verified?: boolean };
export type DirectoryProfileInput = { businessId: string; slug: string; displayName: string; summary: string | null; story: string | null; businessType: OrganizationType; categories: string[]; city: string | null; state: string | null; region: string | null; publicEmail: string | null; publicPhone: string | null; licenseType: string | null; licenseNumber: string | null; links: DirectoryLink[] };
export type DirectoryPage = { profiles: DirectoryProfile[]; pageInfo: { nextCursor: string | null; hasMore: boolean }; nextCursor: string | null; hasMore: boolean };
export type AdminDirectoryProfile = { id: string; organization: { id: string; name: string }; business: { id: string; legalName: string; dbaName: string | null }; workingProfile: Omit<DirectoryProfile, "id" | "status"> & { hasLogo: boolean }; status: ProfileStatus; submittedAt: string | null; hasPublishedVersion: boolean; verificationEligibility: { eligible: boolean; einVerified: boolean; organizationActive: boolean; businessActive: boolean } };
export type ContactRequest = { id: string; status: ContactRequestStatus; routingStatus?: string; firstName?: string; workEmail?: string; phoneNumber?: string; yearsOfService?: number; contactPreference?: ContactPreference; message?: string | null; createdAt: string; updatedAt?: string; target?: { slug: string; displayName: string } };
export type ContactRequestInput = { firstName: string; workEmail: string; phoneNumber: string; yearsOfService: number; contactPreference: ContactPreference; message: string };
export type Notification = { id: string; type: string; category: string; title: string; body: string; resourceType: string | null; resourceId: string | null; createdAt: string; readAt: string | null };
export type NotificationPreferences = Record<"profile" | "contact" | "verification", { inApp: boolean; email: boolean }>;
export type OffsetPage<T> = { items: T[]; pageInfo: { limit: number; offset: number; hasMore: boolean }; limit: number; offset: number; hasMore: boolean; total: number | null };

export class M4ApiError extends Error { readonly status: number; readonly code: string; readonly details?: unknown; constructor(status: number, code: string, message: string, details?: unknown) { super(message); this.name = "M4ApiError"; this.status = status; this.code = code; this.details = details; } }
const object = (value: unknown): Record<string, unknown> => value !== null && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
const string = (value: unknown, fallback = "") => typeof value === "string" ? value : fallback;
const nullable = (value: unknown) => typeof value === "string" ? value : null;
function apiUrl(path: string) { const base = getBridgeApiBase(); if (!base) throw new M4ApiError(0, "API_NOT_CONFIGURED", "The live Bridge API is not configured."); return `${base.replace(/\/$/, "")}${path}`; }
async function request<T>(path: string, init: RequestInit = {}, allow404 = false): Promise<T | null> { let response: Response; try { response = await fetch(apiUrl(path), { ...init, credentials: "include", headers: { Accept: "application/json", ...(init.body ? { "Content-Type": "application/json" } : {}), ...init.headers } }); } catch (cause) { throw new M4ApiError(0, "NETWORK_ERROR", cause instanceof Error ? cause.message : "The API could not be reached."); } const payload = response.status === 204 ? null : await response.json().catch(() => null); if (allow404 && response.status === 404) return null; if (!response.ok) { const error = object(payload); throw new M4ApiError(response.status, string(error.error, "UNKNOWN_ERROR"), string(error.message, `Request failed (${response.status}).`), error.details); } return payload as T; }
function parseProfile(value: unknown): DirectoryProfile { const item = object(value), contact = object(item.publicContact), license = item.license === null ? null : object(item.license); return { id: nullable(item.id) ?? undefined, organizationId: nullable(item.organizationId) ?? undefined, businessId: nullable(item.businessId) ?? undefined, slug: string(item.slug), displayName: string(item.displayName), summary: nullable(item.summary), story: nullable(item.story), businessType: nullable(item.businessType) as OrganizationType | null, categories: Array.isArray(item.categories) ? item.categories.filter((v): v is string => typeof v === "string") : [], city: nullable(item.city), state: nullable(item.state), region: nullable(item.region), publicContact: { email: nullable(contact.email), phone: nullable(contact.phone) }, license: license ? { type: nullable(license.type), number: nullable(license.number) } : null, links: Array.isArray(item.links) ? item.links.map(object).map((v) => ({ type: string(v.type, "other") as DirectoryLink["type"], label: string(v.label), url: string(v.url), sortOrder: Number(v.sortOrder) || 0 })) : [], logoUrl: nullable(item.logoUrl), status: nullable(item.status) as ProfileStatus | undefined, hasPublishedVersion: typeof item.hasPublishedVersion === "boolean" ? item.hasPublishedVersion : undefined, submittedAt: nullable(item.submittedAt), reviewedAt: nullable(item.reviewedAt), workflowReason: nullable(item.workflowReason), approvedAt: nullable(item.approvedAt), legalName: nullable(item.legalName) ?? undefined, dbaName: nullable(item.dbaName), businessName: nullable(item.businessName) ?? undefined, verified: typeof item.verified === "boolean" ? item.verified : undefined }; }
function pageInfo(value: unknown, limit: number, offset: number) { const info = object(value); return { limit: Number.isInteger(info.limit) ? Number(info.limit) : limit, offset: Number.isInteger(info.offset) ? Number(info.offset) : offset, hasMore: info.hasMore === true }; }
function offsetPage<T>(items: T[], info: { limit: number; offset: number; hasMore: boolean }): OffsetPage<T> { return { items, pageInfo: info, ...info, total: null }; }
export function mapAdminAccountChoice(choice: AdminAccountChoice) { return choice === "admin" ? { accountType: "standard" as const, platformRole: "admin" as const } : { accountType: choice, platformRole: null }; }
export function validateAccountSettings(displayName: string, phone: string, initial: { displayName: string | null; phone: string | null }) { const name = displayName.trim(), nextPhone = phone.trim(); const body: { displayName?: string | null; phone?: string | null } = {}; if (name !== (initial.displayName ?? "")) { if (name.length > 100) throw new Error("Display name must be 100 characters or fewer."); body.displayName = name || null; } if (nextPhone !== (initial.phone ?? "")) { if (nextPhone.length > 30) throw new Error("Phone number must be 30 characters or fewer."); body.phone = nextPhone || null; } if (!Object.keys(body).length) throw new Error("Change at least one field before saving."); return body; }

export const m4Api = {
  updateAccount(input: { displayName?: string | null; phone?: string | null }) { return request<{ profile: { displayName: string | null; phone: string | null } }>("/api/v1/auth/me", { method: "PATCH", body: JSON.stringify(input) }); },
  inviteAdminUser(input: { email: string; displayName: string; choice: AdminAccountChoice }) { return request<{ user: { id: string; email: string; displayName: string; accountType: "standard" | "sales_rep"; platformRole: "admin" | null; invitationSent: true } }>("/api/v1/admin/users", { method: "POST", body: JSON.stringify({ email: input.email.trim().toLowerCase(), displayName: input.displayName.trim(), ...mapAdminAccountChoice(input.choice) }) }); },
  async listBusinesses(organizationId: string) { const root = object(await request(`/api/v1/organizations/${encodeURIComponent(organizationId)}/businesses`)); return (Array.isArray(root.businesses) ? root.businesses : []).map((v) => { const b = object(v); return { id: string(b.id), organizationId: string(b.organizationId), legalName: string(b.legalName), dbaName: nullable(b.dbaName), status: string(b.status) }; }); },
  async createBusiness(organizationId: string, input: { legalName: string; dbaName: string | null }) { const root = object(await request(`/api/v1/organizations/${encodeURIComponent(organizationId)}/businesses`, { method: "POST", body: JSON.stringify(input) })); const b = object(root.business); return { id: string(b.id), organizationId: string(b.organizationId), legalName: string(b.legalName), dbaName: nullable(b.dbaName), status: string(b.status) }; },
  async getProfile(organizationId: string) { const value = await request(`/api/v1/organizations/${encodeURIComponent(organizationId)}/directory-profile`, {}, true); return value === null ? null : parseProfile(object(value).profile); },
  async saveProfile(organizationId: string, input: DirectoryProfileInput) { const root = object(await request(`/api/v1/organizations/${encodeURIComponent(organizationId)}/directory-profile`, { method: "PUT", body: JSON.stringify(input) })); return parseProfile(root.profile); },
  async submitProfile(organizationId: string) { const root = object(await request(`/api/v1/organizations/${encodeURIComponent(organizationId)}/directory-profile/submit`, { method: "POST" })); return parseProfile(root.profile); },
  async uploadLogo(organizationId: string, file: File) { const root = object(await request(`/api/v1/organizations/${encodeURIComponent(organizationId)}/directory-profile/logo/upload`, { method: "POST", body: JSON.stringify({ contentType: file.type, fileSize: file.size }) })); const upload = object(root.upload), signedUrl = string(upload.signedUrl), uploadId = string(upload.uploadId), headers = object(upload.requiredHeaders); if (!signedUrl || !uploadId) throw new M4ApiError(500, "INVALID_UPLOAD_RESPONSE", "The backend did not return a complete upload request."); const storage = await fetch(signedUrl, { method: "PUT", headers: Object.fromEntries(Object.entries(headers).filter((entry): entry is [string, string] => typeof entry[1] === "string")), body: file, credentials: "omit" }); if (!storage.ok) throw new M4ApiError(storage.status, "STORAGE_UPLOAD_FAILED", "The logo could not be uploaded to storage."); const complete = object(await request(`/api/v1/organizations/${encodeURIComponent(organizationId)}/directory-profile/logo/complete`, { method: "POST", body: JSON.stringify({ uploadId }) })); return parseProfile(complete.profile); },
  async deleteLogo(organizationId: string) { const root = object(await request(`/api/v1/organizations/${encodeURIComponent(organizationId)}/directory-profile/logo`, { method: "DELETE" })); return parseProfile(root.profile); },
  async listDirectory(filters: { q?: string; organizationType?: OrganizationType; category?: string; state?: string; city?: string; region?: string; verified?: boolean; sort?: DirectorySort; limit?: number; cursor?: string } = {}) { const query = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => { if (value !== undefined && value !== "") query.set(key, String(value)); }); const root = object(await request(`/api/v1/directory/profiles?${query}`)), info = object(root.pageInfo), nextCursor = nullable(info.nextCursor), hasMore = info.hasMore === true; return { profiles: (Array.isArray(root.profiles) ? root.profiles : []).map(parseProfile), pageInfo: { nextCursor, hasMore }, nextCursor, hasMore } as DirectoryPage; },
  async getPublicProfile(slug: string) { const root = object(await request(`/api/v1/directory/profiles/${encodeURIComponent(slug)}`)); return parseProfile(root.profile); },
  async listAdminProfiles(filters: { status?: ProfileStatus; limit?: number; offset?: number } = {}) { const limit = filters.limit ?? 20, offset = filters.offset ?? 0, query = new URLSearchParams({ limit: String(limit), offset: String(offset) }); if (filters.status) query.set("status", filters.status); const root = object(await request(`/api/v1/admin/directory-profiles?${query}`)); const rows = Array.isArray(root.profiles) ? root.profiles : []; const items = rows.map((v) => { const row = object(v), org = object(row.organization), biz = object(row.business), working = parseProfile(row.workingProfile), eligibility = object(row.verificationEligibility); return { id: string(row.id), organization: { id: string(org.id), name: string(org.name) }, business: { id: string(biz.id), legalName: string(biz.legalName), dbaName: nullable(biz.dbaName) }, workingProfile: { ...working, hasLogo: object(row.workingProfile).hasLogo === true }, status: string(row.status) as ProfileStatus, submittedAt: nullable(row.submittedAt), hasPublishedVersion: row.hasPublishedVersion === true, verificationEligibility: { eligible: eligibility.eligible === true, einVerified: eligibility.einVerified === true, organizationActive: eligibility.organizationActive === true, businessActive: eligibility.businessActive === true } }; }); return offsetPage(items, pageInfo(root.pageInfo, limit, offset)); },
  reviewProfile(profileId: string, action: "approve" | "request-correction" | "reject" | "suspend", reason?: string) { return request(`/api/v1/admin/directory-profiles/${encodeURIComponent(profileId)}/${action}`, { method: "POST", ...(action === "approve" ? {} : { body: JSON.stringify({ reason }) }) }); },
  async createContactRequest(slug: string, input: ContactRequestInput) { const root = object(await request(`/api/v1/directory/profiles/${encodeURIComponent(slug)}/contact-requests`, { method: "POST", body: JSON.stringify(input) })); return root.request as ContactRequest; },
  async inbox(organizationId: string, filters: { status?: ContactRequestStatus; limit?: number; offset?: number } = {}) { return contactPage(`/api/v1/organizations/${encodeURIComponent(organizationId)}/contact-requests`, filters); },
  async sent(filters: { limit?: number; offset?: number } = {}) { return contactPage("/api/v1/contact-requests/sent", filters); },
  async updateContactStatus(organizationId: string, requestId: string, status: Exclude<ContactRequestStatus, "new">) { const root = object(await request(`/api/v1/organizations/${encodeURIComponent(organizationId)}/contact-requests/${encodeURIComponent(requestId)}/status`, { method: "POST", body: JSON.stringify({ status }) })); return root.request; },
  async notifications(filters: { unreadOnly?: boolean; limit?: number; offset?: number } = {}) { const limit = filters.limit ?? 20, offset = filters.offset ?? 0, query = new URLSearchParams({ unreadOnly: String(filters.unreadOnly ?? false), limit: String(limit), offset: String(offset) }); const root = object(await request(`/api/v1/notifications?${query}`)); return offsetPage((Array.isArray(root.notifications) ? root.notifications : []) as Notification[], pageInfo(root.pageInfo, limit, offset)); },
  markNotificationRead(id: string) { return request(`/api/v1/notifications/${encodeURIComponent(id)}/read`, { method: "POST" }); }, markAllNotificationsRead() { return request<{ updatedCount: number }>("/api/v1/notifications/read-all", { method: "POST" }); },
  async getNotificationPreferences() { return object(await request("/api/v1/notification-preferences")).preferences as NotificationPreferences; }, async updateNotificationPreferences(preferences: NotificationPreferences) { return object(await request("/api/v1/notification-preferences", { method: "PUT", body: JSON.stringify(preferences) })).preferences as NotificationPreferences; },
};
async function contactPage(path: string, filters: { status?: ContactRequestStatus; limit?: number; offset?: number }) { const limit = filters.limit ?? 20, offset = filters.offset ?? 0, query = new URLSearchParams({ limit: String(limit), offset: String(offset) }); if (filters.status) query.set("status", filters.status); const root = object(await request(`${path}?${query}`)); return offsetPage((Array.isArray(root.requests) ? root.requests : []) as ContactRequest[], pageInfo(root.pageInfo, limit, offset)); }
