"use client";
import { useState, type FormEvent } from "react";
import { useAuth } from "@/components/auth/AuthProvider";
import { M4ApiError, m4Api, validateAccountSettings } from "@/lib/m4/api";
export function AccountSettings() {
  const { user, refresh } = useAuth(); const [displayName, setDisplayName] = useState(() => user?.profile?.displayName ?? ""); const [phone, setPhone] = useState(() => user?.profile?.phone ?? ""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  async function save(event: FormEvent) { event.preventDefault(); setError(""); setNotice(""); let body; try { body = validateAccountSettings(displayName, phone, { displayName: user?.profile?.displayName ?? null, phone: user?.profile?.phone ?? null }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Check the form."); return; } setBusy(true); try { await m4Api.updateAccount(body); await refresh(); setNotice("Account settings saved."); } catch (cause) { setError(cause instanceof M4ApiError && cause.code === "UNAUTHORIZED" ? "Your session expired. Sign in and try again." : cause instanceof Error ? cause.message : "Account settings could not be saved."); } finally { setBusy(false); } }
  return <form className="content-card admin-form" onSubmit={save}><label htmlFor="account-display-name">Display name</label><input id="account-display-name" maxLength={100} value={displayName} onChange={(e) => setDisplayName(e.target.value)} /><label htmlFor="account-email">Email address</label><input id="account-email" value={user?.email ?? ""} readOnly /><label htmlFor="account-phone">Phone number</label><input id="account-phone" maxLength={30} value={phone} onChange={(e) => setPhone(e.target.value)} />{error && <p className="form-error" role="alert">{error}</p>}{notice && <p role="status">{notice}</p>}<button className="button primary" disabled={busy} type="submit">{busy ? "Saving…" : "Save changes"}</button></form>;
}
