"use client";
import { useState, type FormEvent } from "react";
import { m4Api } from "@/lib/m4/api";
type Action = "approve" | "request-correction" | "reject" | "suspend";
const labels: Record<Action, string> = { approve: "Approve", "request-correction": "Request correction", reject: "Reject", suspend: "Suspend" };
export function AdminDirectoryReview() {
  const [profileId, setProfileId] = useState(""); const [action, setAction] = useState<Action>("approve"); const [reason, setReason] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); setNotice(""); try { await m4Api.reviewProfile(profileId.trim(), action, reason.trim() || undefined); setNotice(`${labels[action]} completed for profile ${profileId}.`); setReason(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "The review action could not be completed."); } finally { setBusy(false); } }
  return <div className="form-stack"><p className="boundary-note">The backend has not supplied an admin review-queue endpoint yet. Enter a profile ID from the backend review record to perform an audited action.</p><form className="content-card auth-form" onSubmit={submit}><label htmlFor="admin-profile-id">Directory profile ID</label><input id="admin-profile-id" required value={profileId} onChange={(event) => setProfileId(event.target.value)} /><label htmlFor="admin-profile-action">Action</label><select id="admin-profile-action" value={action} onChange={(event) => { setAction(event.target.value as Action); setReason(""); }}><option value="approve">Approve</option><option value="request-correction">Request correction</option><option value="reject">Reject</option><option value="suspend">Suspend</option></select>{action !== "approve" && <><label htmlFor="admin-profile-reason">Reason</label><textarea id="admin-profile-reason" required maxLength={2000} rows={5} value={reason} onChange={(event) => setReason(event.target.value)} /></>}{error && <p className="form-error" role="alert">{error}</p>}{notice && <p role="status">{notice}</p>}<button className="button primary" disabled={busy} type="submit">{busy ? "Submitting…" : labels[action]}</button></form></div>;
}
