"use client";
import Link from "next/link";
import { useState, type FormEvent } from "react";
import { M4ApiError, m4Api, type AdminAccountChoice } from "@/lib/m4/api";
const errors: Record<string, string> = { ADMIN_USER_ALREADY_EXISTS: "A user with this email already exists.", UNAUTHORIZED: "Your session expired. Sign in and try again.", FORBIDDEN: "You do not have permission to invite users.", ADMIN_USER_INVITATION_FAILED: "The invitation could not be sent. No account was created.", ADMIN_USERS_UNAVAILABLE: "User invitations are temporarily unavailable. Try again later." };
export default function CreateAdminUserPage() {
  const [email, setEmail] = useState(""); const [displayName, setDisplayName] = useState(""); const [choice, setChoice] = useState<AdminAccountChoice | "">(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setNotice(""); if (!email.trim() || !displayName.trim() || !choice) { setError("Email, display name, and account type are required."); return; } if (!event.currentTarget.checkValidity()) { event.currentTarget.reportValidity(); return; } setBusy(true); try { const result = await m4Api.inviteAdminUser({ email, displayName, choice }); if (result?.user.invitationSent !== true) throw new Error("The server did not confirm that an invitation was sent."); setNotice(`Invitation sent to ${result.user.email}.`); setEmail(""); setDisplayName(""); setChoice(""); } catch (cause) { setError(cause instanceof M4ApiError ? errors[cause.code] ?? cause.message : cause instanceof Error ? cause.message : "The invitation could not be sent."); } finally { setBusy(false); } }
  return <><Link className="admin-back-link" href="/admin/users">← Back to users</Link><div className="dashboard-heading"><div><p className="eyebrow">User management</p><h1>Invite user</h1><p className="lede">Supabase will email a secure invitation. The user sets their own password.</p></div></div><form className="content-card admin-form" onSubmit={submit}><label htmlFor="new-name">Display name</label><input id="new-name" required maxLength={100} value={displayName} onChange={(e) => setDisplayName(e.target.value)} /><label htmlFor="new-email">Email address</label><input id="new-email" required maxLength={254} type="email" value={email} onChange={(e) => setEmail(e.target.value)} /><label htmlFor="role">Account access</label><select id="role" required value={choice} onChange={(e) => setChoice(e.target.value as AdminAccountChoice)}><option value="" disabled>Select account access</option><option value="standard">Standard User</option><option value="sales_rep">Sales Representative</option><option value="admin">Platform Administrator</option></select>{error && <p className="form-error" role="alert">{error}</p>}{notice && <p role="status">{notice}</p>}<button className="button primary" disabled={busy} type="submit">{busy ? "Sending invitation…" : "Send invitation"}</button></form></>;
}
